spring:
    datasource:
        houses:
            url: jdbc:sqlite:data/houses.db
            driver-class-name: org.sqlite.JDBC
            username: ""
            password: ""
            platform: ""
            jpa:
                database-platform: org.hibernate.dialect.SQLiteDialect
            initialization-mode: always
        universities:
            url: jdbc:sqlite:data/universities.db
            driver-class-name: org.sqlite.JDBC
            username: ""
            password: ""
            platform: ""
            jpa:
               database-platform: org.hibernate.dialect.SQLiteDialect
            initialization-mode: always
        means:
           url: jdbc:sqlite:data/means.db
           driver-class-name: org.sqlite.JDBC
           username: ""
           password: ""
           platform: ""
           jpa:
               database-platform: org.hibernate.dialect.SQLiteDialect
           initialization-mode: always
        
        server:
            port: 8080

